sudo: required
language: node_js
node_js:
  - 7
services:
  - docker

before_install:
  - docker build -t erifleit/dr -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
